# Generated by Django 4.1.3 on 2022-12-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_added',
            field=models.DateTimeField(default='2022-12-10T04:27:20.307778+00:00'),
        ),
    ]
